metrics:
- labels:
  - label_description: The original name of the metric as collected by Prometheus.
    label_name: __name__
  metric_description: null
  metric_name: cluster:route_metrics_controller_routes_per_shard:median
  type: null
- labels:
  - label_description: The original name of the metric as collected by Prometheus.
    label_name: __name__
  metric_description: null
  metric_name: cluster:route_metrics_controller_routes_per_shard:min
  type: null
- labels:
  - label_description: The original name of the metric as collected by Prometheus.
    label_name: __name__
  metric_description: null
  metric_name: cluster:route_metrics_controller_routes_per_shard:avg
  type: null
- labels:
  - label_description: The original name of the metric as collected by Prometheus.
    label_name: __name__
  metric_description: null
  metric_name: cluster:route_metrics_controller_routes_per_shard:max
  type: null
