metrics:
- labels:
  - label_description: The original name of the metric as collected by Prometheus.
    label_name: __name__
  metric_description: null
  metric_name: cluster:ingress_controller_aws_nlb_active:sum
  type: null
