metrics:
- labels:
  - label_description: The original name of the metric as collected by Prometheus.
    label_name: __name__
  - label_description: null
    label_name: source
  - label_description: null
    label_name: location
  metric_description: null
  metric_name: imageregistry:imagestreamtags_count:sum
  type: null
