metrics:
- labels:
  - label_description: The original name of the metric as collected by Prometheus.
    label_name: __name__
  - label_description: The specific instance of the monitored service or application,
      typically represented by an IP address or hostname.
    label_name: instance
  - label_description: null
    label_name: apiserver
  metric_description: null
  metric_name: instance:apiserver_longrunning_requests:sum
  type: null
- labels:
  - label_description: The original name of the metric as collected by Prometheus.
    label_name: __name__
  - label_description: The specific instance of the monitored service or application,
      typically represented by an IP address or hostname.
    label_name: instance
  - label_description: null
    label_name: apiserver
  metric_description: null
  metric_name: instance:apiserver_request_total:rate1m
  type: null
- labels:
  - label_description: The original name of the metric as collected by Prometheus.
    label_name: __name__
  - label_description: The specific instance of the monitored service or application,
      typically represented by an IP address or hostname.
    label_name: instance
  - label_description: null
    label_name: apiserver
  metric_description: null
  metric_name: instance:apiserver_response_sizes_sum:rate1m
  type: null
- labels:
  - label_description: The original name of the metric as collected by Prometheus.
    label_name: __name__
  - label_description: The specific instance of the monitored service or application,
      typically represented by an IP address or hostname.
    label_name: instance
  - label_description: null
    label_name: apiserver
  metric_description: null
  metric_name: instance:apiserver_response_sizes_sum:rate5m
  type: null
- labels:
  - label_description: The original name of the metric as collected by Prometheus.
    label_name: __name__
  - label_description: The specific instance of the monitored service or application,
      typically represented by an IP address or hostname.
    label_name: instance
  - label_description: null
    label_name: apiserver
  metric_description: null
  metric_name: instance:apiserver_request_total:rate5m
  type: null
