metrics:
- labels:
  - label_description: The original name of the metric as collected by Prometheus.
    label_name: __name__
  - label_description: The specific instance of the monitored service or application,
      typically represented by an IP address or hostname.
    label_name: instance
  - label_description: null
    label_name: completion_mode
  - label_description: The name of the pod in which the container is running.
    label_name: pod
  - label_description: null
    label_name: le
  - label_description: The name of the Prometheus job that is responsible for scraping
      the metrics.
    label_name: job
  - label_description: null
    label_name: action
  - label_description: The name of the Kubernetes service that the metrics are associated
      with.
    label_name: service
  - label_description: The specific endpoint of the service or application being monitored.
    label_name: endpoint
  - label_description: The Kubernetes namespace in which the pod or service resides.
    label_name: namespace
  - label_description: null
    label_name: result
  - label_description: The name of the container within a pod that is being monitored.
    label_name: container
  metric_description: null
  metric_name: job_controller_job_sync_duration_seconds_bucket
  type: null
- labels:
  - label_description: The original name of the metric as collected by Prometheus.
    label_name: __name__
  - label_description: The specific instance of the monitored service or application,
      typically represented by an IP address or hostname.
    label_name: instance
  - label_description: null
    label_name: completion_mode
  - label_description: The name of the pod in which the container is running.
    label_name: pod
  - label_description: The name of the Prometheus job that is responsible for scraping
      the metrics.
    label_name: job
  - label_description: The name of the Kubernetes service that the metrics are associated
      with.
    label_name: service
  - label_description: The specific endpoint of the service or application being monitored.
    label_name: endpoint
  - label_description: The Kubernetes namespace in which the pod or service resides.
    label_name: namespace
  - label_description: null
    label_name: result
  - label_description: The name of the container within a pod that is being monitored.
    label_name: container
  metric_description: '[STABLE] The number of finished Pods that are fully tracked'
  metric_name: job_controller_job_pods_finished_total
  type: counter
- labels:
  - label_description: The original name of the metric as collected by Prometheus.
    label_name: __name__
  - label_description: The specific instance of the monitored service or application,
      typically represented by an IP address or hostname.
    label_name: instance
  - label_description: null
    label_name: completion_mode
  - label_description: The name of the pod in which the container is running.
    label_name: pod
  - label_description: The name of the Prometheus job that is responsible for scraping
      the metrics.
    label_name: job
  - label_description: null
    label_name: action
  - label_description: The name of the Kubernetes service that the metrics are associated
      with.
    label_name: service
  - label_description: The specific endpoint of the service or application being monitored.
    label_name: endpoint
  - label_description: The Kubernetes namespace in which the pod or service resides.
    label_name: namespace
  - label_description: null
    label_name: result
  - label_description: The name of the container within a pod that is being monitored.
    label_name: container
  metric_description: null
  metric_name: job_controller_job_sync_duration_seconds_count
  type: null
- labels:
  - label_description: The original name of the metric as collected by Prometheus.
    label_name: __name__
  - label_description: The specific instance of the monitored service or application,
      typically represented by an IP address or hostname.
    label_name: instance
  - label_description: null
    label_name: completion_mode
  - label_description: The name of the pod in which the container is running.
    label_name: pod
  - label_description: The name of the Prometheus job that is responsible for scraping
      the metrics.
    label_name: job
  - label_description: null
    label_name: action
  - label_description: The name of the Kubernetes service that the metrics are associated
      with.
    label_name: service
  - label_description: The specific endpoint of the service or application being monitored.
    label_name: endpoint
  - label_description: The Kubernetes namespace in which the pod or service resides.
    label_name: namespace
  - label_description: null
    label_name: result
  - label_description: The name of the container within a pod that is being monitored.
    label_name: container
  metric_description: null
  metric_name: job_controller_job_sync_duration_seconds_sum
  type: null
- labels:
  - label_description: The original name of the metric as collected by Prometheus.
    label_name: __name__
  - label_description: The specific instance of the monitored service or application,
      typically represented by an IP address or hostname.
    label_name: instance
  - label_description: The name of the pod in which the container is running.
    label_name: pod
  - label_description: The name of the Prometheus job that is responsible for scraping
      the metrics.
    label_name: job
  - label_description: The name of the Kubernetes service that the metrics are associated
      with.
    label_name: service
  - label_description: The specific endpoint of the service or application being monitored.
    label_name: endpoint
  - label_description: null
    label_name: reason
  - label_description: The Kubernetes namespace in which the pod or service resides.
    label_name: namespace
  - label_description: null
    label_name: status
  - label_description: The name of the container within a pod that is being monitored.
    label_name: container
  metric_description: '[ALPHA] The number of Pods created by the Job controller labelled
    with a reason for the Pod creation.

    This metric also distinguishes between Pods created using different PodReplacementPolicy
    settings.

    Possible values of the "reason" label are:

    "new", "recreate_terminating_or_failed", "recreate_failed".

    Possible values of the "status" label are:

    "succeeded", "failed".'
  metric_name: job_controller_job_pods_creation_total
  type: counter
- labels:
  - label_description: The original name of the metric as collected by Prometheus.
    label_name: __name__
  - label_description: The specific instance of the monitored service or application,
      typically represented by an IP address or hostname.
    label_name: instance
  - label_description: null
    label_name: completion_mode
  - label_description: The name of the pod in which the container is running.
    label_name: pod
  - label_description: The name of the Prometheus job that is responsible for scraping
      the metrics.
    label_name: job
  - label_description: null
    label_name: action
  - label_description: The name of the Kubernetes service that the metrics are associated
      with.
    label_name: service
  - label_description: The specific endpoint of the service or application being monitored.
    label_name: endpoint
  - label_description: The Kubernetes namespace in which the pod or service resides.
    label_name: namespace
  - label_description: null
    label_name: result
  - label_description: The name of the container within a pod that is being monitored.
    label_name: container
  metric_description: '[STABLE] The number of job syncs'
  metric_name: job_controller_job_syncs_total
  type: counter
- labels:
  - label_description: The original name of the metric as collected by Prometheus.
    label_name: __name__
  - label_description: The name of the Prometheus job that is responsible for scraping
      the metrics.
    label_name: job
  - label_description: null
    label_name: route
  - label_description: null
    label_name: status_code
  - label_description: The Kubernetes namespace in which the pod or service resides.
    label_name: namespace
  metric_description: null
  metric_name: job_namespace_route_statuscode:loki_request_duration_seconds_count:irate1m
  type: null
- labels:
  - label_description: The original name of the metric as collected by Prometheus.
    label_name: __name__
  - label_description: The specific instance of the monitored service or application,
      typically represented by an IP address or hostname.
    label_name: instance
  - label_description: null
    label_name: completion_mode
  - label_description: The name of the pod in which the container is running.
    label_name: pod
  - label_description: The name of the Prometheus job that is responsible for scraping
      the metrics.
    label_name: job
  - label_description: The name of the Kubernetes service that the metrics are associated
      with.
    label_name: service
  - label_description: The specific endpoint of the service or application being monitored.
    label_name: endpoint
  - label_description: null
    label_name: reason
  - label_description: The Kubernetes namespace in which the pod or service resides.
    label_name: namespace
  - label_description: null
    label_name: result
  - label_description: The name of the container within a pod that is being monitored.
    label_name: container
  metric_description: '[STABLE] The number of finished jobs'
  metric_name: job_controller_jobs_finished_total
  type: counter
- labels:
  - label_description: The original name of the metric as collected by Prometheus.
    label_name: __name__
  - label_description: The specific instance of the monitored service or application,
      typically represented by an IP address or hostname.
    label_name: instance
  - label_description: The name of the pod in which the container is running.
    label_name: pod
  - label_description: The name of the Prometheus job that is responsible for scraping
      the metrics.
    label_name: job
  - label_description: The name of the Kubernetes service that the metrics are associated
      with.
    label_name: service
  - label_description: The specific endpoint of the service or application being monitored.
    label_name: endpoint
  - label_description: The Kubernetes namespace in which the pod or service resides.
    label_name: namespace
  - label_description: null
    label_name: event
  - label_description: The name of the container within a pod that is being monitored.
    label_name: container
  metric_description: '[ALPHA] The number of terminated pods (phase=Failed|Succeeded)

    that have the finalizer batch.kubernetes.io/job-tracking

    The event label can be "add" or "delete".'
  metric_name: job_controller_terminated_pods_tracking_finalizer_total
  type: counter
- labels:
  - label_description: The original name of the metric as collected by Prometheus.
    label_name: __name__
  - label_description: null
    label_name: le
  - label_description: The name of the Prometheus job that is responsible for scraping
      the metrics.
    label_name: job
  - label_description: null
    label_name: route
  metric_description: null
  metric_name: job_route:loki_request_duration_seconds_bucket:sum_rate
  type: null
- labels:
  - label_description: The original name of the metric as collected by Prometheus.
    label_name: __name__
  - label_description: The name of the Prometheus job that is responsible for scraping
      the metrics.
    label_name: job
  - label_description: null
    label_name: route
  metric_description: null
  metric_name: job_route:loki_request_duration_seconds_count:sum_rate
  type: null
- labels:
  - label_description: The original name of the metric as collected by Prometheus.
    label_name: __name__
  - label_description: The name of the Prometheus job that is responsible for scraping
      the metrics.
    label_name: job
  - label_description: null
    label_name: route
  metric_description: null
  metric_name: job_route:loki_request_duration_seconds_sum:sum_rate
  type: null
