metrics:
- labels:
  - label_description: The original name of the metric as collected by Prometheus.
    label_name: __name__
  - label_description: The Kubernetes namespace in which the pod or service resides.
    label_name: namespace
  metric_description: null
  metric_name: monitoring:container_memory_working_set_bytes:sum
  type: null
