metrics:
- labels:
  - label_description: The original name of the metric as collected by Prometheus.
    label_name: __name__
  - label_description: The Kubernetes namespace in which the pod or service resides.
    label_name: namespace
  - label_description: The name of the pod in which the container is running.
    label_name: pod
  metric_description: null
  metric_name: pod:container_fs_usage_bytes:sum
  type: null
- labels:
  - label_description: The original name of the metric as collected by Prometheus.
    label_name: __name__
  - label_description: The Kubernetes namespace in which the pod or service resides.
    label_name: namespace
  - label_description: The name of the pod in which the container is running.
    label_name: pod
  metric_description: null
  metric_name: pod:container_cpu_usage:sum
  type: null
